version: '3.8'

services:
  local-mysql:
    image: mysql:latest
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: local@1234
    ports:
      - "3306:3306"
    networks:
      - database-network
  local-mongodb:
    image: mongo:latest
    container_name: local-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - database-network

networks:
  database-network:
    driver: bridge


# RUN: docker-compose up -d
# Verify comand: docker-compose ps
# Kill: docker-compose down
